sep24:
  #  Port this server is being ran on
  port: 8091
  #  URL for anchor platform server
  anchorPlatformUrl: "http://localhost:8080"
  #  URL for horizon server
  horizonUrl: "https://horizon-testnet.stellar.org"
  #  Secret key used to send funds to user accounts
  secret: "SCQ2YRUGKBO4Q6RWSXV3SYVGHJB525XVKUP2HDGVW3LV42UBLGTZ24XX"
  # When true, enables test endpoints
  enableTest: true
  # Encryption key for interactive JWT
  interactiveJwtKey: "sep24 interactive url secret"