version: '2.4'
services:
  anchor-platform:
    image: stellar/anchor-platform:edge
    command: --anchor-reference-server --sep-server --stellar-observer
    environment:
      - STELLAR_ANCHOR_CONFIG=file:/config/anchor-docker-compose-config.yaml
      - REFERENCE_SERVER_CONFIG_ENV=file:/reference-config/anchor-reference-server-docker-compose-config.yaml
      - KT_REFERENCE_SERVER_CONFIG=/kt-ref-config/docker-config.yaml
      - LOG_APPENDER=console_appender
      - SECRET_DATA_USERNAME=postgres
      - SECRET_DATA_PASSWORD=password
      - SECRET_PLATFORM_API_AUTH_SECRET=myAnchorToPlatformSecret
      - SECRET_CALLBACK_API_AUTH_SECRET=myPlatformToAnchorSecret
      - SECRET_SEP10_JWT_SECRET=secret
      - SECRET_SEP10_SIGNING_SEED=SAX3AH622R2XT6DXWWSRIDCMMUCCMATBZ5U6XKJWDO7M2EJUBFC3AW5X
      - SECRET__SEP24KEY=SECRET__SEP24KEY=SDYGC4TW5HHR5JA6CB2XLTTBF2DZRH2KDPBDPV3D5TXM6GF7FBPRZF3I
    depends_on:
      - db
      - kafka
    volumes:
      - ./platform/src/main/resources:/config
      - ./anchor-reference-server/src/main/resources:/reference-config
      - ./kotlin-reference-server/src/main/resources:/kt-ref-config
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8091:8091"

  db:
    image: postgres:latest
    ports:
      - "5431:5432"  # use 5431 so this doesn't conflict if you have a local postgres instance running
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  zookeeper:
    platform: linux/x86_64
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    platform: linux/x86_64
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
