app_logging.level:
app_logging.request_logger_enabled:
app_logging.stellar_level:
assets.type:
assets.value:
callback_api.auth.api_key.http_header:
callback_api.auth.jwt.expiration_milliseconds:
callback_api.auth.jwt.http_header:
callback_api.auth.type:
callback_api.base_url:
callback_api.check_certificate:
clients:
data.database:
data.ddl_auto:
data.flyway_baseline_on_migrate:
data.flyway_enabled:
data.flyway_location:
data.initial_connection_pool_size:
data.max_active_connections:
data.server:
data.type:
event_processor.callback_api_request.enabled:
event_processor.client_status_callback.enabled:
event_processor.context_path:
event_processor.port:
events.enabled:
events.event_type_to_queue.quote_created:
events.event_type_to_queue.transaction_created:
events.event_type_to_queue.transaction_error:
events.event_type_to_queue.transaction_status_changed:
events.publisher.kafka.batch_size:
events.publisher.kafka.bootstrap_server:
events.publisher.kafka.client_id:
events.publisher.kafka.linger_ms:
events.publisher.kafka.retries:
events.publisher.msk.batch_size:
events.publisher.msk.bootstrap_server:
events.publisher.msk.client_id:
events.publisher.msk.linger_ms:
events.publisher.msk.retries:
events.publisher.msk.use_iam:
events.publisher.sqs.aws_region:
events.publisher.sqs.use_iam:
events.publisher.type:
languages:
metrics.enabled:
metrics.extras_enabled:
metrics.run_interval:
payment_observer.context_path:
payment_observer.port:
payment_observer.stellar.initial_event_backoff_time:
payment_observer.stellar.initial_stream_backoff_time:
payment_observer.stellar.max_event_backoff_time:
payment_observer.stellar.max_stream_backoff_time:
payment_observer.stellar.silence_check_interval:
payment_observer.stellar.silence_timeout:
payment_observer.stellar.silence_timeout_retries:
payment_observer.type:
platform_api.auth.api_key.http_header:
platform_api.auth.jwt.expiration_milliseconds:
platform_api.auth.jwt.http_header:
platform_api.auth.type:
platform_api.base_url:
platform_server.auth.api_key.http_header:
platform_server.auth.jwt.http_header:
platform_server.auth.type:
platform_server.context_path:
platform_server.port:
sep1.enabled:
sep1.toml.type:
sep1.toml.value:
sep10.auth_timeout:
sep10.client_attribution_allow_list:
sep10.client_attribution_deny_list:
sep10.client_attribution_required:
sep10.enabled:
sep10.home_domain:
sep10.jwt_timeout:
sep10.omnibus_account_list:
sep10.require_known_omnibus_account:
sep10.web_auth_domain:
sep12.enabled:
sep24.enabled:
sep24.features.account_creation:
sep24.features.claimable_balances:
sep24.interactive_url.base_url:
sep24.interactive_url.jwt_expiration:
sep24.interactive_url.txn_fields:
sep24.kyc_fields_forwarding.enabled:
sep24.more_info_url.base_url:
sep24.more_info_url.jwt_expiration:
sep24.more_info_url.txn_fields:
sep31.deposit_info_generator_type:
sep31.enabled:
sep31.payment_type:
sep38.enabled:
sep_server.context_path:
sep_server.management_server_port:
sep_server.port:
stellar_network.horizon_url:
stellar_network.network:
stellar_network.network_passphrase: