assets.type:
assets.value:
callback_api.auth.expiration_milliseconds:
callback_api.auth.type:
callback_api.base_url:
data.ddl_auto:
data.flyway_enabled:
data.flyway_location:
data.initial_connection_pool_size:
data.max_active_connections:
data.password:
data.type:
data.url:
data.username:
events.enabled:
events.event_type_to_queue.quote_created:
events.event_type_to_queue.transaction_created:
events.event_type_to_queue.transaction_error:
events.event_type_to_queue.transaction_status_changed:
events.publisher.kafka.batch_size:
events.publisher.kafka.bootstrap_servers:
events.publisher.kafka.client_id:
events.publisher.kafka.linger_ms:
events.publisher.kafka.retries:
events.publisher.msk.aws_region:
events.publisher.msk.bootstrap_server:
events.publisher.msk.client_id:
events.publisher.msk.linger_ms:
events.publisher.msk.retries:
events.publisher.msk.use_iam:
events.publisher.sqs.aws_region:
events.publisher.sqs.use_iam:
events.publisher.type:
host_url:
languages:
logging.level:
logging.stellar_level:
metrics.enabled:
metrics.extras_enabled:
metrics.run_interval:
payment_observer.circle_url:
payment_observer.enabled:
payment_observer.tracked_wallet:
platform_api.auth.expiration_milliseconds:
platform_api.auth.type:
secret.callback_api.secret:
secret.jwt_secret:
secret.platform_api.secret:
secret.sep10_signing_seed:
sep1.enabled:
sep1.toml.type:
sep1.toml.value:
sep10.auth_timeout:
sep10.client_attribution_allow_list:
sep10.client_attribution_deny_list:
sep10.client_attribution_required:
sep10.enabled:
sep10.home_domain:
sep10.jwt_timeout:
sep10.omnibus_account_list:
sep10.require_known_omnibus_account:
sep12.enabled:
sep24.enabled:
sep24.interactive_jwt_expiration:
sep24.interactive_url:
sep31.deposit_info_generator_type:
sep31.enabled:
sep31.payment_type:
sep38.enabled:
stellar_network.horizon_url:
stellar_network.network:
stellar_network.network_passphrase: