app_logging.level:
app_logging.request_logger_enabled:
app_logging.stellar_level:
assets.type:
assets.value:
callback_api.auth.api_key.http_header:
callback_api.auth.jwt.expiration_milliseconds:
callback_api.auth.jwt.http_header:
callback_api.auth.type:
callback_api.base_url:
callback_api.check_certificate:
clients:
data.database:
data.ddl_auto:
data.flyway_baseline_on_migrate:
data.flyway_enabled:
data.flyway_location:
data.initial_connection_pool_size:
data.max_active_connections:
data.server:
data.type:
event_processor.callback_api_request.enabled:
event_processor.client_status_callback.enabled:
event_processor.context_path:
event_processor.port:
events.enabled:
events.queue.kafka.batch_size:
events.queue.kafka.bootstrap_server:
events.queue.kafka.client_id:
events.queue.kafka.linger_ms:
events.queue.kafka.poll_timeout_seconds:
events.queue.kafka.retries:
events.queue.msk.batch_size:
events.queue.msk.bootstrap_server:
events.queue.msk.client_id:
events.queue.msk.linger_ms:
events.queue.msk.retries:
events.queue.msk.use_iam:
events.queue.sqs.aws_region:
events.queue.sqs.use_iam:
events.queue.type:
languages:
metrics.enabled:
metrics.extras_enabled:
metrics.run_interval:
payment_observer.context_path:
payment_observer.port:
payment_observer.stellar.initial_event_backoff_time:
payment_observer.stellar.initial_stream_backoff_time:
payment_observer.stellar.max_event_backoff_time:
payment_observer.stellar.max_stream_backoff_time:
payment_observer.stellar.silence_check_interval:
payment_observer.stellar.silence_timeout:
payment_observer.stellar.silence_timeout_retries:
payment_observer.type:
platform_api.auth.api_key.http_header:
platform_api.auth.jwt.expiration_milliseconds:
platform_api.auth.jwt.http_header:
platform_api.auth.type:
platform_api.base_url:
platform_server.auth.api_key.http_header:
platform_server.auth.jwt.http_header:
platform_server.auth.type:
platform_server.context_path:
platform_server.port:
sep1.enabled:
sep1.toml.type:
sep1.toml.value:
sep10.auth_timeout:
sep10.client_attribution_required:
sep10.enabled:
sep10.home_domain:
sep10.jwt_timeout:
sep10.known_custodial_account_required:
sep10.web_auth_domain:
sep12.enabled:
sep24.enabled:
sep24.features.account_creation:
sep24.features.claimable_balances:
sep24.interactive_url.base_url:
sep24.interactive_url.jwt_expiration:
sep24.interactive_url.txn_fields:
sep24.kyc_fields_forwarding.enabled:
sep24.more_info_url.base_url:
sep24.more_info_url.jwt_expiration:
sep24.more_info_url.txn_fields:
sep24.deposit_info_generator_type:
sep31.deposit_info_generator_type:
sep31.enabled:
sep31.payment_type:
sep38.enabled:
sep6.enabled:
sep6.features.account_creation:
sep6.features.claimable_balances:
sep_server.context_path:
sep_server.management_server_port:
sep_server.port:
stellar_network.horizon_url:
stellar_network.network:
stellar_network.network_passphrase:
custody_server.context_path:
custody_server.port:
custody_server.auth.api_key.http_header:
custody_server.auth.jwt.expiration_milliseconds:
custody_server.auth.jwt.http_header:
custody_server.auth.type:
custody_server.base_url:
custody_server.http_client.connect_timeout:
custody_server.http_client.read_timeout:
custody_server.http_client.write_timeout:
custody_server.http_client.call_timeout:
custody.type:
custody.http_client.connect_timeout:
custody.http_client.read_timeout:
custody.http_client.write_timeout:
custody.http_client.call_timeout:
custody.trustline.check_cron_expression:
custody.trustline.check_duration:
custody.trustline.check_timeout_message:
custody.fireblocks.base_url:
custody.fireblocks.vault_account_id:
custody.fireblocks.public_key:
custody.fireblocks.retry_config.max_attempts:
custody.fireblocks.retry_config.delay:
custody.fireblocks.asset_mappings:
custody.fireblocks.reconciliation.cron_expression:
custody.fireblocks.reconciliation.max_attempts:
rpc.custom_messages.custody_transaction_failed:
rpc.custom_messages.incoming_payment_received:
rpc.custom_messages.outgoing_payment_sent:
rpc.batch_size_limit: