apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: anchor-platform
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/frame-deny: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
    ingress.kubernetes.io/hsts-max-age: "31536000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
spec:
  tls:
    - hosts:
      - www.stellaranchordemo.com
      secretName: letsencrypt-staging
  ingressClassName: nginx
  rules:
  - host: www.stellaranchordemo.com
    http:
      paths:
      - path: /info
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /transactions
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /.well-known/stellar.toml
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /auth
        pathType: Exact
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /sep6
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /sep12
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080      
      - path: /sep24
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /sep31
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /sep38
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
  
