version: 1

logging:
  level: INFO
  stellar_level: DEBUG

callback_api:
  base_url: http://localhost:8081
  auth:
    type: none

platform_api:
  auth:
    type: none

events:
  enabled: true
  publisher:
    kafka:
      bootstrap_server: kafka:29092

sep1:
  enabled: true
  toml:
    type: string
    value: |
      ACCOUNTS = []
      VERSION = "0.1.0"
      NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
      SIGNING_KEY = "GCHLHDBOKG2JWMJQBTLSL5XG6NO7ESXI2TAQKZXCXWXB5WI2X6W233PR"
      
      WEB_AUTH_ENDPOINT = "http://localhost:8080/auth"
      KYC_SERVER = "http://localhost:8080/sep12"
      TRANSFER_SERVER_SEP0024 = "http://localhost:8080/sep24"
      DIRECT_PAYMENT_SERVER = "http://localhost:8080/sep31"
      ANCHOR_QUOTE_SERVER = "http://localhost:8080/sep38"
      
      [[CURRENCIES]]
      code = "USDC"
      issuer = "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
      status = "test"
      is_asset_anchored = true
      anchor_asset_type = "fiat"
      desc = "A test USDC issued by Stellar."
      
      [[CURRENCIES]]
      code = "JPYC"
      issuer = "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
      status = "test"
      is_asset_anchored = true
      anchor_asset_type = "fiat"
      desc = "A test JPYC issued by Stellar."

sep10:
  enabled: true
  home_domain: localhost:8080

sep12:
  enabled: true

sep24:
  enabled: true

sep31:
  enabled: true

sep38:
  enabled: true

assets:
  type: json
  value: |
    {
      "assets": [
          {
              "schema": "stellar",
              "code": "USDC",
              "issuer": "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
             "distribution_account": "GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF",
              "significant_decimals": 2,
              "deposit" : {
                  "enabled": true,
                  "fee_minimum": 0,
                  "fee_percent": 0,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "withdraw": {
                  "enabled": true,
                  "fee_fixed": 0,
                  "fee_percent": 0,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "send": {
                  "fee_fixed": 0,
                  "fee_percent": 0,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "sep31" : {
                  "quotes_supported": true,
                  "quotes_required": false,
                  "sep12": {
                      "sender": {
                          "types": {
                              "sep31-sender": {
                                  "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                              },
                              "sep31-large-sender": {
                                  "description": "U.S. citizens that do not have sending limits"
                              },
                              "sep31-foreign-sender": {
                                  "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                              }
                          }
                      },
                      "receiver": {
                          "types": {
                              "sep31-receiver": {
                                  "description": "U.S. citizens receiving USD"
                              },
                              "sep31-foreign-receiver": {
                                  "description": "non-U.S. citizens receiving USD"
                              }
                          }
                      }
                  },
                  "fields": {
                      "transaction": {
                          "receiver_routing_number": {
                              "description": "routing number of the destination bank account"
                          },
                          "receiver_account_number": {
                              "description": "bank account number of the destination"
                          },
                          "type": {
                              "description": "type of deposit to make",
                              "choices": [
                                  "SEPA",
                                  "SWIFT"
                              ]
                          }
                      }
                  }
              },
              "sep38": {
                  "exchangeable_assets": [
                      "iso4217:USD"
                  ]
              },
              "sep24_enabled": true,
              "sep31_enabled": true,
              "sep38_enabled": true
          },
          {
              "schema": "stellar",
              "code": "JPYC",
              "issuer": "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
              "distribution_account": "GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF",
              "significant_decimals": 4,
              "deposit" : {
                  "enabled": true,
                  "fee_minimum": 0,
                  "fee_percent": 0,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "withdraw": {
                  "enabled": true,
                  "fee_fixed": 0,
                  "fee_percent": 0,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "send": {
                  "fee_fixed": 0,
                  "fee_percent": 0,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "sep31" : {
                  "quotes_supported": true,
                  "quotes_required": false,
                  "sep12": {
                      "sender": {
                          "types": {
                              "sep31-sender": {
                                  "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                              },
                              "sep31-large-sender": {
                                  "description": "U.S. citizens that do not have sending limits"
                              },
                              "sep31-foreign-sender": {
                                  "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                              }
                          }
                      },
                      "receiver": {
                          "types": {
                              "sep31-receiver": {
                                  "description": "U.S. citizens receiving JPY"
                              },
                              "sep31-foreign-receiver": {
                                  "description": "non-U.S. citizens receiving JPY"
                              }
                          }
                      }
                  },
                  "fields": {
                      "transaction": {
                          "receiver_routing_number": {
                              "description": "routing number of the destination bank account"
                          },
                          "receiver_account_number": {
                              "description": "bank account number of the destination"
                          },
                          "type": {
                              "description": "type of deposit to make",
                              "choices": [
                                  "SEPA",
                                  "SWIFT"
                              ]
                          }
                      }
                  }
              },
              "sep38": {
                  "exchangeable_assets": [
                      "iso4217:USD"
                  ]
              },
              "sep24_enabled": true,
              "sep31_enabled": true,
              "sep38_enabled": true
          },
          {
              "schema": "iso4217",
              "code": "USD",
              "deposit" : {
                  "enabled": true,
                  "fee_minimum": 0,
                  "fee_percent": 0,
                  "min_amount": 0,
                  "max_amount": 10000
              },
              "withdraw": {
                  "enabled": true,
                  "fee_fixed": 0,
                  "fee_percent": 0,
                  "min_amount": 0,
                  "max_amount": 10000
              },
              "send": {
                  "fee_fixed": 0,
                  "fee_percent": 0,
                  "min_amount": 0,
                  "max_amount": 10000
              },
              "sep38": {
                  "exchangeable_assets": [
                      "stellar:USDC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
                      "stellar:JPYC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
                  ],
                  "country_codes": ["USA"],
                  "decimals": 4,
                  "sell_delivery_methods": [
                      {
                          "name": "WIRE",
                          "description": "Send USD directly to the Anchor's bank account."
                      }
                  ],
                  "buy_delivery_methods": [
                      {
                          "name": "WIRE",
                          "description": "Have USD sent directly to your bank account."
                      }
                  ]
              },
              "sep24_enabled": false,
              "sep31_enabled": false,
              "sep38_enabled": true
          }
      ]
    }

################################
## Data Configuration
################################
data:

  ## DB credentials are specified in @environment_variables SECRET_DATA_USERNAME, SECRET_DATA_PASSWORD

  ## @param: type
  ## @supported_values:
  ##    `h2` (in-memory), `sqlite` (local), `postgres` (local), `aurora` (postgres on AWS)
  ## Type of storage.
  ## If this is set to `aurora`,
  ##    @required_secrets: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
  #
  type: postgres

  server: db:5432

  database: postgres

  ## @param: initial_connection_pool_size
  ## @type: integer
  ## Initial number of connections
  ## For `sqlite`, set this to 1 to avoid database file lock exception
  #
  initial_connection_pool_size: 1

  ## @param: max_active_connections
  ## @type: integer
  ## Maximum number of db active connections
  ## For `sqlite`, set this to 1 to avoid database file lock exception
  #
  max_active_connections: 10

  ## @param: flyway_enabled
  ## @type: bool
  ## Whether to enable flyway.
  ## Should be disabled for `sqlite` because certain features that flyway uses
  ## (ex: addForeignKeyConstraint) are not supported.
  #
  flyway_enabled: true

  ## @param: flyway_enabled
  ## @type: string
  ## Location on disk where migrations are stored if flyway is enabled.
  #
  flyway_location: /db/migration

  ## @param: hikari_max_lifetime
  ## @type: integer
  ## Maximum connection time before expiration
  ## Only valid when database `type` is `aurora`.
  ## Recommended setting is 14 minutes because IAM tokens are valid for 15 min.
  #
  # hikari_max_lifetime: 840000
