stellar:
  anchor:
    config: in-memory                             # Configure the application from this file after it is loaded in memory
    app-config:
      type: config-spring-property                # Activate [config-spring-property] module
      settings: config-spring-property-settings   # The location of the configuration data in this file.
    data-access:
      type: data-spring-jdbc                      # Activate [config-spring-jdbc] module.
      settings: data-spring-jdbc-settings         # The location of the configuration data in this file.
    logging:
      type: logging-logback
      settings: logging-logback-settings
    payment-gateway:
      services:
        - payment-circle                  # Activate [payment-circle] module
        - payment-stellar                # Activate [payment-stellar] module

#
# Application settings
#
config-spring-property-settings:
  # general
  app:
    stellarNetworkPassPhrase: Test SDF Network ; September 2015
    hostUrl: http://localhost:8080
    languages: en
    horizonURI: https://horizon-testnet.stellar.org
    assets: assets-test.json
    jwtSecretKey: secret

  # sep-1
  sep1:
    enabled: true
    stellarFile: sep1/stellar-wks.toml

  # sep-10
  sep10:
    enabled: true
    homeDomain: localhost:8080
    clientAttributionRequired: false
    clientAttributionAllowList: lobstr.co,preview.lobstr.co
    authTimeout: 900
    jwtTimeout: 86400
    signingSeed: 
    omnibusAccountList:

  # sep-24
  sep24:
    interactiveJwtExpiration: 300
    interactiveUrl: http://localhost:8080/ref/sep24/interactive

#
# Payment Circle configurations
#
payment-circle:
  payment.circle:
    enabled: true
    name: "circle_payment"
    url: http://payment.circle.com
    secretKey: This-is-a-secret-key

#
# Payment Stellar configurations
#
payment-stellar:
  payment.stellar:
    enabled: false
    name: "stellar_payment"
    horizon_url: http://payment.stellar.org
    secretKey: This-is-a-secret-key

#
# Spring Data JDBC settings
#
data-spring-jdbc-settings:
  spring.jpa.database-platform: org.stellar.anchor.server.sqlite.SQLiteDialect
  spring.jpa.hibernate.ddl-auto: update
  spring.jpa.generate-ddl: true
  spring.jpa.hibernate.show_sql: false
  spring.datasource.url: jdbc:sqlite:anchor-proxy.db
  spring.datasource.driver-class-name: org.sqlite.JDBC
  spring.datasource.username: admin
  spring.datasource.password: admin

#
# Spring framework configurations
#
spring:
  logging:
    level:
      root: INFO
      org.springframework: INFO
      org.springframework.web.filter: INFO
      org.stellar: DEBUG
  server:
    servlet:
      context-path: "/"
  mvc:
    async.request-timeout: 6000
