version: 1

host_url: http://localhost:8080

stellar_network:
  network: TESTNET
  network_passphrase: Test SDF Network ; September 2015
  horizon_url: https://horizon-testnet.stellar.org

callback_api:
  base_url: http://localhost:8081
  auth:
    type: none

platform_api:
  auth:
    type: none

languages: en

logging:
  level: WARN
  stellar_level: INFO

data:
  type: sqlite
  database: anchor-platform
  initial_connection_pool_size: 2
  max_active_connections: 10
  flyway_enabled: true
  ddl_auto: update

#data:
#  type: postgres
#  server: localhost:5432
#  database: postgres
#  username: anchorplatform
#  password:
#  initial_connection_pool_size: 3
#  max_active_connections: 10
#  flyway_enabled: true
#  ddl_auto: update

sep1:
  enabled: true
  toml:
    type: string
    value: |
      ACCOUNTS = []
      VERSION = "0.1.0"
      NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
      SIGNING_KEY = "GBDYDBJKQBJK4GY4V7FAONSFF2IBJSKNTBYJ65F5KCGBY2BIGPGGLJOH"
      
      WEB_AUTH_ENDPOINT = "http://localhost:8080/auth"
      KYC_SERVER = "http://localhost:8080/sep12"
      TRANSFER_SERVER_SEP0024 = "http://localhost:8080/sep24"
      DIRECT_PAYMENT_SERVER = "http://localhost:8080/sep31"
      ANCHOR_QUOTE_SERVER = "http://localhost:8080/sep38"
      
      [[CURRENCIES]]
      code = "USDC"
      issuer = "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
      status = "test"
      is_asset_anchored = true
      anchor_asset_type = "fiat"
      desc = "A test USDC issued by Stellar."
      
      [[CURRENCIES]]
      code = "JPYC"
      issuer = "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
      status = "test"
      is_asset_anchored = true
      anchor_asset_type = "fiat"
      desc = "A test JPYC issued by Stellar."

sep10:
  enabled: true
  home_domain: localhost:8080

sep12:
  enabled: true

sep24:
  enabled: true
  interactive_url:
    base_url: http://localhost:3000

sep31:
  enabled: true
  payment_type: STRICT_SEND
  deposit_info_generator_type: self

sep38:
  enabled: true

metrics:
  enabled: true
  extras_enabled: true
  run_interval: 30

events:
  enabled: false
  event_type_to_queue:
    quote_created: ap_event_quote_created
    transaction_created: ap_event_transaction_created
    transaction_status_changed: ap_event_transaction_status_changed
    transaction_error: ap_event_transaction_error
  publisher:
    type: kafka
    kafka:
      bootstrap_server: localhost:29092
      client_id:
      retries: 1
      linger_ms: 1000
      batch_size: 10

assets:
  type: json
  value: |
    {
      "assets": [
        {
          "schema": "stellar",
          "code": "USDC",
          "issuer": "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
          "distribution_account": "GABCKCYPAGDDQMSCTMSBO7C2L34NU3XXCW7LR4VVSWCCXMAJY3B4YCZP",
          "significant_decimals": 2,
          "deposit": {
            "enabled": true,
            "fee_minimum": 0,
            "fee_percent": 0,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "withdraw": {
            "enabled": true,
            "fee_fixed": 0,
            "fee_percent": 0,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "send": {
            "fee_fixed": 0,
            "fee_percent": 0,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "sep31": {
            "quotes_supported": true,
            "quotes_required": false,
            "sep12": {
              "sender": {
                "types": {
                  "sep31-sender": {
                    "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                  },
                  "sep31-large-sender": {
                    "description": "U.S. citizens that do not have sending limits"
                  },
                  "sep31-foreign-sender": {
                    "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                  }
                }
              },
              "receiver": {
                "types": {
                  "sep31-receiver": {
                    "description": "U.S. citizens receiving USD"
                  },
                  "sep31-foreign-receiver": {
                    "description": "non-U.S. citizens receiving USD"
                  }
                }
              }
            },
            "fields": {
              "transaction": {
                "receiver_routing_number": {
                  "description": "routing number of the destination bank account"
                },
                "receiver_account_number": {
                  "description": "bank account number of the destination"
                },
                "type": {
                  "description": "type of deposit to make",
                  "choices": [
                    "SEPA",
                    "SWIFT"
                  ]
                }
              }
            }
          },
          "sep38": {
            "exchangeable_assets": [
              "iso4217:USD"
            ]
          },
          "sep24_enabled": true,
          "sep31_enabled": true,
          "sep38_enabled": true
        },
        {
          "schema": "stellar",
          "code": "JPYC",
          "issuer": "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
          "distribution_account": "GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF",
          "significant_decimals": 4,
          "deposit": {
            "enabled": true,
            "fee_minimum": 0,
            "fee_percent": 0,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "withdraw": {
            "enabled": true,
            "fee_fixed": 0,
            "fee_percent": 0,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "send": {
            "fee_fixed": 0,
            "fee_percent": 0,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "sep31": {
            "quotes_supported": true,
            "quotes_required": false,
            "sep12": {
              "sender": {
                "types": {
                  "sep31-sender": {
                    "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                  },
                  "sep31-large-sender": {
                    "description": "U.S. citizens that do not have sending limits"
                  },
                  "sep31-foreign-sender": {
                    "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                  }
                }
              },
              "receiver": {
                "types": {
                  "sep31-receiver": {
                    "description": "U.S. citizens receiving JPY"
                  },
                  "sep31-foreign-receiver": {
                    "description": "non-U.S. citizens receiving JPY"
                  }
                }
              }
            },
            "fields": {
              "transaction": {
                "receiver_routing_number": {
                  "description": "routing number of the destination bank account"
                },
                "receiver_account_number": {
                  "description": "bank account number of the destination"
                },
                "type": {
                  "description": "type of deposit to make",
                  "choices": [
                    "SEPA",
                    "SWIFT"
                  ]
                }
              }
            }
          },
          "sep38": {
            "exchangeable_assets": [
              "iso4217:USD"
            ]
          },
          "sep24_enabled": true,
          "sep31_enabled": true,
          "sep38_enabled": true
        },
        {
          "schema": "iso4217",
          "code": "USD",
          "deposit": {
            "enabled": true,
            "fee_minimum": 0,
            "fee_percent": 0,
            "min_amount": 0,
            "max_amount": 10000
          },
          "withdraw": {
            "enabled": true,
            "fee_fixed": 0,
            "fee_percent": 0,
            "min_amount": 0,
            "max_amount": 10000
          },
          "send": {
            "fee_fixed": 0,
            "fee_percent": 0,
            "min_amount": 0,
            "max_amount": 10000
          },
          "sep38": {
            "exchangeable_assets": [
              "stellar:USDC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
              "stellar:JPYC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
            ],
            "country_codes": [
              "USA"
            ],
            "decimals": 4,
            "sell_delivery_methods": [
              {
                "name": "WIRE",
                "description": "Send USD directly to the Anchor's bank account."
              }
            ],
            "buy_delivery_methods": [
              {
                "name": "WIRE",
                "description": "Have USD sent directly to your bank account."
              }
            ]
          },
          "sep24_enabled": false,
          "sep31_enabled": false,
          "sep38_enabled": true
        }
      ]
    }
