version: '2.4'
services:
  platform:
    image: stellar/anchor-platform:edge
    command: --sep-server
    environment:
      - stellar_anchor_config=file:/config/anchor-config.yaml
      # secrets
      - secret.data.username=postgres
      - secret.data.password=password
      - secret.platform_api.auth_secret=myAnchorToPlatformSecret
      - secret.callback_api.auth_secret=myPlatformToAnchorSecret
      - secret.sep10.jwt_secret=secret_sep10_secret
      - secret.sep10.signing_seed=SAX3AH622R2XT6DXWWSRIDCMMUCCMATBZ5U6XKJWDO7M2EJUBFC3AW5X
      - secret.sep24.interactive_url.jwt_secret=secret_sep24_interactive_url_jwt_secret
      - secret.sep24.more_info_url.jwt_secret=secret_sep24_more_info_url_jwt_secret
      # logging
      - logging.stellar_level=DEBUG
      # events
      - events.enabled=true
      - events.publisher.type=kafka
      - events.publisher.kafka.bootstrap_server=kafka:29092
      # data
      - data.type=postgres
      - data.url=jdbc:postgresql://db:5432/
      - data.flyway_enabled=false
      # seps
      - sep1.enabled=true
      - sep10.enabled=true
      - sep10.home_domain=localhost:8080
      - sep24.enabled=true
      - sep24.interactive_url.base_url=https://stellar.moneygram.com
      - sep24.more_info_url.base_url=http://localhost:8080/sep24/transaction/more_info
    depends_on:
      - db
      - kafka
      - reference_server
    volumes:
      - .:/config
    ports:
      - "8080:8080" # sep-server
      - "8082:8082" # Java management server

  reference_server:
    extends:
      file: ../common-services/common-services.yaml
      service: reference_server_a

  kafka:
    extends:
      file: ../common-services/common-services.yaml
      service: kafka_a

  zookeeper:
    extends:
      file: ../common-services/common-services.yaml
      service: zookeeper_a

  db:
    extends:
      file: ../common-services/common-services.yaml
      service: db_a


