ACCOUNTS = []
VERSION = "0.1.0"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
SIGNING_KEY = "GCHLHDBOKG2JWMJQBTLSL5XG6NO7ESXI2TAQKZXCXWXB5WI2X6W233PR"

WEB_AUTH_ENDPOINT = "http://host.docker.internal:8080/auth"
KYC_SERVER = "http://host.docker.internal:8080/sep12"
TRANSFER_SERVER_SEP0024 = "http://host.docker.internal:8080/sep24"
DIRECT_PAYMENT_SERVER = "http://host.docker.internal:8080/sep31"
ANCHOR_QUOTE_SERVER = "http://host.docker.internal:8080/sep38"

[[CURRENCIES]]
code = "USDC"
issuer = "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
desc = "A test USDC issued by Stellar."

[[CURRENCIES]]
code = "JPYC"
issuer = "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
desc = "A test JPYC issued by Stellar."