version: '2.4'
services:
  reference_server:
#    image: stellar/anchor-platform:edge
    build:
      context: ../../
      dockerfile: Dockerfile
    command: --anchor-reference-server
    environment:
      - REFERENCE_SERVER_CONFIG_ENV=file:/config/anchor-reference-server.yaml
    depends_on:
      - db
      - kafka
    volumes:
      - .:/config
    ports:
      - "8081:8081" # reference-server
    extra_hosts:
      - "host.docker.internal:host-gateway"

  observer:
#    image: stellar/anchor-platform:edge
    build:
      context: ../../
      dockerfile: Dockerfile
    command: "--stellar-observer"
    environment:
      # override configs
      - stellar.anchor.config=file:/config/anchor-config-defaults.yaml
      # secrets
      - secret.sep10.signing_seed=SAKXNWVTRVR4SJSHZUDB2CLJXEQHRT62MYQWA2HBB7YBOTCFJJJ55BZF
      - secret.sep10.jwt_secret=secret
      - secret.platform.api_auth_secret=myAnchorToPlatformSecret
      - secret.callback.api_auth_secret=myPlatformToAnchorSecret
      - secret.data.username=postgres
      - secret.data.password=password
      # assets
      - assets.type=file
      - assets.value=/config/assets.yaml
    depends_on:
      - db
      - kafka
      - reference_server
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kafka:
    platform: linux/x86_64
    image: confluentinc/cp-kafka:6.1.9
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: host.docker.internal:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zookeeper:
    platform: linux/x86_64
    image: confluentinc/cp-zookeeper:6.1.9
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGPORT=5432
    extra_hosts:
      - "host.docker.internal:host-gateway"