# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  find_test_url:
    runs-on: ubuntu-latest
    name: Finds server URL
    env:
      PR_NUMBER: ${{github.event.pull_request.number}}
    steps:
      - name: Find Server URL (Preview or Dev)
        run: |
          export ENDPOINT=https://anchor-sep-server-dev.stellar.org/
          if [ ! -z "$PR_NUMBER" ]
          then
            export ENDPOINT=https://anchor-sep-pr$PR_NUMBER.previews.kube001.services.stellar-ops.com
          fi
          echo ENDPOINT=$ENDPOINT
          echo "::set-output name=ENDPOINT::$ENDPOINT"

      - name: Validate endpoint
        run: echo ENDPOINT=$ENDPOINT

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Clean, Build and Test
      run: |
        ./gradlew clean build
        echo *** Core test report ***
        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/core/build/reports/tests/test/index.html
        echo *** Payment Circle test report ***
        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/payment-circle/build/reports/tests/test/index.html
        echo *** Platform test report ***
        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/platform/build/reports/tests/test/index.html
        echo *** Anchor reference server test report ***
        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/anchor-reference-server/build/reports/tests/test/index.html

  build_and_push_anchor_platform:
    if: github.event.pull_request == null
    needs: [build_and_test]
    runs-on: ubuntu-latest
    name: Push stellar/anchor-platform:sha to DockerHub
    steps:
    - uses: actions/checkout@v3
    
    - name: Get image tag (short sha)
      shell: bash
      id: get_tag
      run: echo ::set-output name=TAG::$(git rev-parse --short ${{ github.sha }} )

    - name: Login to DockerHub
      uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
      with:
        push: true
        tags: stellar/anchor-platform:${{ steps.get_tag.outputs.TAG }}
        file: Dockerfile

  sep_validation_suite:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    name: Validate SEPs (1, 10, 12, 31, 38)
    steps:
      - uses: actions/checkout@v3

      # Find the PR associated with this push, if there is one.
      - name: Find PR number
        uses: jwalton/gh-find-current-pr@465461f2b0e83dd1a57b3a04e7c81050705f7391
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run Validation Tool
        env:
          PR: ${{ steps.findPr.outputs.pr }}
        run: |
          npm install -g @stellar/anchor-tests
          stellar-anchor-tests --home-domain https://anchor-sep-pr$PR.previews.kube001.services.stellar-ops.com --seps 1 10 12 31 38 --sep-config platform/src/test/resources/stellar-anchor-tests-sep-config.json
