name: Gradle Build and Test

on:
  # allows this workflow to be called from another workflow
  workflow_dispatch:
  workflow_call:

jobs:
  gradle_test_and_build:
    name: Gradle Test and Build
    runs-on: ubuntu-22.04
    steps:
      # Start the docker containers
      - uses: actions/checkout@v3
      - name: Build the stack
        env:
          TEST_PROFILE_NAME: default
        run: docker-compose -f service-runner/src/main/resources/docker-compose-test.yaml up -d --build

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Check the docker containers
      - name: Check running containers
        run: docker ps

      # This is to add to DNS entries to access the services started by docker-compose.
      - name: Add 'db' and 'kafka' to /etc/hosts
        run: |
          sudo echo "127.0.0.1 db" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 kafka" | sudo tee -a /etc/hosts
          sudo nslookup db
          sudo nslookup kafka

      # Gradle test is now printing the test messages to GitHub Actions log. It is not necessary to print the reports.
      - name: Test and Build
        env:
          TEST_PROFILE_NAME: default
          run_docker: false
        run: ./gradlew integration-tests:test --stacktrace

  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
