name: Generate Jacoco Coverage Report

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      forceRebuild:
        type: boolean
        description: 'Force Gradle rebuild (true/false)'
        required: false
        default: false

jobs:
  jacoco-report:
    name: Generate Jacoco Coverage Report
    runs-on: ubuntu-latest
    steps:
      #############################################
      # Setup JDK 17
      # Download, and Extract java-stellar-anchor-sdk.tar
      # Setup hostnames (/etc/hosts)
      #############################################
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Download java-stellar-anchor-sdk.tar
        uses: actions/download-artifact@v4.1.7
        with:
          name: java-stellar-anchor-sdk-tar
          path: /home/runner/

      - name: Extract java-stellar-anchor-sdk.tar
        run: |
          cd /home/runner
          tar -xf /home/runner/java-stellar-anchor-sdk.tar
          cd /home/runner/java-stellar-anchor-sdk

      - name: Set up hostnames (/etc/hosts)
        run: |
          sudo echo "127.0.0.1 db" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 kafka" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 sep24-reference-ui" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 reference-server" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 reference-db" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 wallet-server" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 platform" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 custody-server" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts 

      #############################################
      - name: Gradle Build with unit tests only
        if : ${{ inputs.forceRebuild }}
        run: |
          cd /home/runner/java-stellar-anchor-sdk
          ./gradlew clean build jacocoTestReport -x essential-tests:test -x extended-tests:test

      - name: Add coverage to the Pull Request
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          # The path to the jacocoTestReport.xml files which were generated in the previous workflow
          paths: /home/runner/java-stellar-sdk/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          update-comment: true