name: Release Published

on:
  workflow_dispatch:
  push:
    # when commits are pushed or merged onto `develop` branch
    branches: [ release/2.0.0-preview-1 ]
  release:
    types: [ created, edited ]

jobs:
  end_to_end_tests:
    name: Run end-to-end Tests
    uses: ./.github/workflows/sub_end_to_end_tests.yml
    secrets: inherit
  
  build_and_push_docker_image:
    name: Push to DockerHub (tag=stellar/anchor-platform:${{ github.event.release.tag_name }})
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Get anchor platform project version
        shell: bash
        id: get_version
        run: echo ::set-output name=VERSION::$(${{github.workspace}}/gradlew -q printVersionName)

      - name: Echo versions
        run: echo "Release version=${{ github.event.release.tag_name }}, Project version=${{ steps.get_version.outputs.VERSION }}"

#      - name: Fail if the release version and the project version do not match
#        if: ${{ '${{ github.event.release.tag_name }}' != '${{ steps.get_version.outputs.VERSION }}' }}
#        run: exit 1

      - name: Get current date
        id: get_date
        run: echo "::set-output name=DATE::$(date +'%Y-%m-%d')"

      - name: Calculate Github SHA
        shell: bash
        id: get_sha
        run: echo ::set-output name=SHA::$(git rev-parse --short ${{ github.sha }} )

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          push: true
          #          tags: stellar/anchor-platform:${{ github.event.release.tag_name }}-rc,stellar/anchor-platform:latest
          tags: stellar/anchor-platform:test-rc
          file: Dockerfile

  complete:
    if: always()
    # TODO: Enable end_to_end tests after it is fixed.
    #    needs: [ end_to_end_tests, build_and_push_docker_image ]
    needs: [ build_and_push_docker_image ]
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
