# This workflow will build a docker image and push to docker hub
# This workflow is triggered:
#   1. When commits are pushed or merged onto `develop` branch
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Push/Merge to `develop` Branch

on:
  push:
    # when commits are pushed or merged onto `develop` branch
    branches: [ develop ]

jobs:
  gradle_test_and_build:
    uses: ./.github/workflows/sub_gradle_test_and_build.yml

  # TODO: enable the SEP validation when the develop deployment is fixed.
#  sep_validation_suite:
#    needs: [ gradle_test_and_build ]
#    uses: ./.github/workflows/sub_stellar_anchor_tests.yml

  # TODO: enable end_to_end_tests after it is fixed.
#  end_to_end_tests:
#    name: Run end-to-end Tests
#    uses: ./.github/workflows/sub_end_to_end_tests.yml
#    secrets: inherit

  build_and_push_docker_image:
    # stellar/anchor-platform:edge-${{ steps.get_date.outputs.date }}-${{ steps.get_sha.outputs.SHA }}
    # and stellar/anchor-platform:edge
    name: Push to DockerHub (tag=stellar/anchor-platform:edge)
    #    needs: [ gradle_test_and_build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Calculate Github SHA
        shell: bash
        id: get_sha
        run: echo "SHA=$(git rev-parse --short ${{ github.sha }} )" >> $GITHUB_OUTPUT

      - name: Build and push to DockerHub with tags `edge` and `edge-{date}-{sha}`
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          push: true
          tags: stellar/anchor-platform:edge,stellar/anchor-platform:edge-${{ steps.get_date.outputs.DATE }}-${{ steps.get_sha.outputs.SHA }}
          file: Dockerfile

  # TODO: enable purge-image when we got the dockerhub token
  #  purge-image:
  #    name: Purge Docker edge Images (tags=edge-*)
  #    runs-on: ubuntu-22.04
  #    steps:
  #      - name: Delete image
  #        uses: bots-house/ghcr-delete-image-action@v1.1.0
  #        with:
  #          owner: stellarproducteng
  #          name: ${{ secrets.DOCKERHUB_USERNAME }}
  #          token: ${{ secrets.DOCKERHUB_TOKEN }}
  #          tag: edge-*

  complete:
    if: always()
    # TODO: add sep_validation_suite when Jenkins develop build is complete
    needs: [ gradle_test_and_build, build_and_push_docker_image ]
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1